app:
  allow_origins: [
    "http://127.0.0.1",
    "https://badminton-kub.netlify.app",
  ]

redis:
  host: redis://red-d12ge1juibrs73f6kqs0:6379

mongo:
  uri: mongodb://localhost:27017
  database: badminton_service
